version: '3.3'

services:
  api:
    build: ./backend
    environment:
      FLASK_ENV: ${FLASK_ENV:-"production"}
      FLASK_APP: "app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app
    container_name: api
    command: "flask run --host=0.0.0.0"
    networks:
      backend:

networks:
  backend:
  frontend:
