version: '3.3'

services:
  api:
    build: ./backend
    environment:
      FLASK_ENV: ${FLASK_ENV:-production}
      FLASK_APP: "app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./backend/:/app
    container_name: api
    command: "flask run --host=0.0.0.0"
    networks:
      backend:
      frontend:
  ui:
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    container_name: ui
    command: "npm start"
    networks:
      frontend:
  mongo:
    image: mongo
    volumes:
      - ./mongodata:/data/db
    ports:
      - "27017:27017"
    container_name:  mongo
    networks:
      backend:
  redis:
    image: redis:alpine
    container_name:  redis
    networks:
      backend:

networks:
  backend:
  frontend:
